export const GET_SINGLE_PRODUCT_LOADING = "loading/GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_ERROR = "error/GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_SUCCESS = "success/GET_SINGLE_PRODUCT";

